services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: m2c
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: rabbit         
      RABBITMQ_DEFAULT_PASS: senha123 