services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: m2c
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"